[package]
name = "liveview-native-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
categories.workspace = true
keywords.workspace = true
license-file.workspace = true
readme.workspace = true
publish.workspace = true

build = "build.rs"

[lib]
name = "liveview_native_core"
crate-type = ["staticlib", "rlib", "cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cranelift-entity = "0.87"
fixedbitset = "0.4"
fxhash = "0.2"
html5gum = { git = "https://github.com/liveviewnative/html5gum", branch = "lvn" }
intrusive-collections = { version = "0.9", features = ["nightly"] }
indexmap = { version = "1.7", features = ["std"] }
lazy_static = "1.4"
paste = "1.0"
petgraph = { version = "0.6", default-features = false, features = ["graphmap"] }
smallvec = { version = "1.9", features = ["union", "const_generics", "specialization"] }
smallstr = { version = "0.3", features = ["union"] }
thiserror = "1.0"
jni = "0.21.0"
log = "0.4.17"
log-panics = { version = "2", features = ["with-backtrace"]}
android_logger = "0.13.1"

[build-dependencies]
Inflector = "0.11"
